### PR TITLE
Capstone Project (ISUMMIT Website)

### PR DESCRIPTION
**Pull request by aliatayee**
## Capstone Project (ISUMMIT Website)
in this milestone, i have created the final capstone project with the following properties:
- Home page structures defined in index.html.
- About page structures defined in about.html.
- Featured speakers data passed dynamically in featured-speakers.js.
- All styles applied in custome.css & about.css.
- please find the video presentation link bellow:
- https://www.loom.com/share/a54fc0d1b5704b1593f9d39d77808c9b

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @aliatayee  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Video Presentation is missing, Please record a video on loom presenting your project and add the recording link in your ReadMe file. 👍🏻 
- [ ] You've added the wrong live link. It should be your capstone project link.
- [ ] The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
- [ ] Cover page is stick to the top, Kindly add some padding to make it look clean and accessible. 👍🏻 
Screen Shot 2022-05-21 at 7 51 45 PM

- [ ] In mobile screen, navbar is supposed to cover the whole screen. 
Screen Shot 2022-05-21 at 7 53 22 PM

- [ ] In mobile screen, Footer section is missing. Kindly add the footer section in mobile screen. 👍🏻 
Screen Shot 2022-05-21 at 8 06 39 PM

- [ ] Font size is too small in mobile screen, Kindly increase the font size in mobile version to make it more readable. 👍🏻 
Screen Shot 2022-05-21 at 8 08 38 PM

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by phelian23 — CHANGES_REQUESTED** [review]
Hi @aliatayee, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] As requested by the previous reviewer, Kindly increase the fonts of text for the mobile version of your project
Your design
Capture

Capture1


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aliatayee** [comment]
@zainsadaqat thank you bro
Please find the video link in PR description

**Comment by aliatayee** [comment]
@phelian23 bro i have increased the fonts as well for me it is working fine. Please check once again

**Comment by aliatayee** [comment]
Dear reviwer,
Since this is my last try, i hope you consider optional changes if there is anything left !

**Review by RolandM99 — APPROVED** [review]
<h1>Status: Approve 🥇 ✔</h1>
Hi @aliatayee , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

- [ ]  [ **OPTIONAL** ] As requested by the previous reviewer, It'll be better if you add the font-size of your about page content. Also, It would be better if you add an close button for your menu pop-up.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
